services:
  app:
    depends_on:
      - database
    build:
      context: .
      args:
        - ENV=dev
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: uvicorn main:create_app --host 0.0.0.0 --reload --factory
    volumes:
      - ./src:/app/src/
      - ./tests:/app/tests/

  database:
    image: postgres:16.2-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    expose:
      - "5432"
    volumes:
      - "${DB_DATA_VOLUME:-db-data}:/var/lib/postgresql/data"

volumes:
  db-data:
