[tool.isort]
profile = "black"
filter_files = true
line_length = 88
known_third_party = "fastapi"
src_paths = "."

[tool.flake8]
max-line-length = 88
extend-ignore = [
    "DC100", "D100",
]
exclude = [
    ".git",
    "__pycache__",
]
inline-quotes = '"'
